[platformio]
default_envs = esp32dev

[env]
framework = arduino
monitor_speed = 115200
; Cambia el número de práctica (1-8)
; Selección de driver por defecto: A4988 (quitar y usar -DSTEPPER_ULN2003 si corresponde)
build_flags = -DPRACTICE=1 -DSTEPPER_A4988

[env:esp32dev]
platform = espressif32
board = esp32dev
upload_speed = 921600
build_flags = ${env.build_flags} -DARDUINO_ARCH_ESP32

[env:pico]
platform = raspberrypi
board = pico
build_flags = ${env.build_flags} -DARDUINO_ARCH_RP2040

; Ejemplo alternativo si usas ULN2003 en alguna práctica:
; [env:pico_uln]
; platform = raspberrypi
; board = pico
; build_flags = -DPRACTICE=8 -DSTEPPER_ULN2003 -DARDUINO_ARCH_RP2040
